language: python
sudo: false

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
matrix:
  include:
    - python: 3.6

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels conda-forge
  - conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file requirements/build.txt
  - conda install pip
  - pip install -r requirements/pip.txt
  - pip install .


script:
  - conda install --file requirements/run.txt
  - conda install --yes --file requirements/test.txt
  - pip install codecov pytest-env
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - sidewind -h
  - sidewind init test .
  - sidewind nomad -h
  - flake8 sidewinder_spec
#  - conda install --yes --file requirements/docs.txt
#  - pip install git+git://github.com/drdoctr/doctr.git
#  - cd docs
#  - make html
#  - cd ..
#  - doctr deploy . --built-docs ./docs/_build/html;